export const ADD_INGREIDENT = 'ADD_INGREIDENT';
export const REMOVE_INGREIDENT = 'REMOVE_INGREIDENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
